# Generated by Django 5.0.4 on 2024-04-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_alter_myuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
